# Generated by Django 4.2 on 2023-04-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='genter',
            new_name='gender',
        ),
    ]
