# Generated by Django 4.1.7 on 2023-04-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostDB',
        ),
    ]
